### ISSUE TITLE
Bug: Edit Location: Dropdown for Meetings Settings not preselected - jumps to default.

### ISSUE THREAD

**Issue by malano** [imGraetzl/im_graetzl#224]
If i set the Meeting-Option in the Dropdown to "Nur ich kann Treffen hier starten" it will be saved.

But if i edit the Location afterwards, the Setting is not Selected correctly, so it jumps back to "Jeder kann Treffen hier starten". But the User doesn't recognise that when editing and saves with the wrong option ...

**Comment by tld3112** [comment]
Hi @malano,

I am new to this organisation and would like to work on this issue. Could you please guide me a little more so that I can better understand what needs to be done?

**Comment by malano** [comment]
Hi @tld3112,

Thanks for your Interest!
So the first step would be to bring the App running on your Localhost. We have an introduction in our Readme File how to do this. May its a little tricky for the first time, but if you have any Problems, for sure you can contact us.

Or its already  running on your localhost?
If it works, than you can register a User and afterwards you can create an location for this user. Just visit this url with your logged-In user: "/user/locations" (btw right top in the Navigation, you have the menue-point "Locations").

Locations have to approved by an admin, but you can create an admin user for imGrätzl.at on your localhost. Once you are admin, you have access to the admin-interface, where you can approve your new location....

Just let me know if the app is running and you are able to login, afterwards i can describe you a little bit more the occurring bug.

Thanks, cheers
michael

**Comment by tld3112** [comment]
Hi Michael,

Sorry for the delayed response. We had a few difficulties setting up the localhost, but have finally managed to get the app running and login as an admin. Could you please help guide us further through to the bug?

**Comment by malano** [comment]
Cool that you get it running! Great!

Regarding this issue:
So first it would be necessary that you setup a location for your user.
for this, go logged-in to: https://www.imgraetzl.at/user/locations setup your location and make the settings for meetings "Nur ich kann treffen hier starten".

After that you have to got into the Admin-tool as an Admin and there you have to approve your new location: https://www.imgraetzl.at/admin/locations

After that go back to the Location and click on "Edit" - btw. "Location bearbeiten". Then you can see your Settings, and you will see that the Dropdown "Nur ich kann treffen hier starten" is not saved, so it shows the default option ... For sure the Settings of the User should be shown here ...

Let me know regarding further questions ...

Cheers, 
Michael
