### ISSUE TITLE
Bug: Raumteiler Contact Website URLs are mostly incorrect ..

### ISSUE THREAD

**Issue by malano** [imGraetzl/im_graetzl#225]
hey drazen

The Website Contact Fields on the Raumteiler Pages have mostly incorrect values, because there was no validation of this field. I just changed the input-type to "type=url" so that we have a basic browser validation - but actually most of the addresses we have in the database are false and the links are generating 404s ... (see screenshot status line)

may we can run a script over all the raumteiler website contact data, and add an "http://" at the beginning, if the url does not start with http or https ...

<img width="1106" alt="bildschirmfoto 2018-03-11 um 21 29 49" src="https://user-images.githubusercontent.com/44798/37258186-17a12fee-2574-11e8-887d-c32d5b10b9f0.png">

thanks,
michael

**Comment by metakermit** [comment]
@malano ok, I can do that on the existing urls. Also, adding this validation to the form is a nice first issue to work on, I think, so I opened it here:

https://github.com/imGraetzl/im_graetzl/issues/226

Feel free to expand on it if there are urls in other parts of the app as well (besides for just the Raumteiler).

**Comment by malano** [comment]
ok, thx for info @metakermit
