### ISSUE TITLE
Validate urls in new room descriptions

### ISSUE THREAD

**Issue by metakermit** [imGraetzl/im_graetzl#226]
When users submit content, e.g. [create new rooms](https://www.imgraetzl.at/wien/raumteiler/raum/select), they can add urls. If these urls don't start with `http://` clicking on them results in a 404 – the browser tries to find that page on our site instead of opening a new site.

See e.g. [this page](https://www.imgraetzl.at/wien/raumteiler/raum/biete-auslagenflache-prasentationstische-ausstellungsflache) and click the `www.sonnentor.com/Wien-Landstrasse` link (you only see it if you're logged in).

Expected behaviour – the pap should automatically prepend `http://` if the user didn't add that part on their own.

Related to issue https://github.com/imGraetzl/im_graetzl/issues/225.

**Comment by utsha1510** [comment]
I'm logged in but I didn't see the link. can you direct me a bit more so that I can understand the issue better?

**Comment by metakermit** [comment]
Hi @utsha1510 sure. So when you log in, you can create different types of content (locations, meetings, and _rooms_). You can see the new content menu in the top right corner "Neu Erstellen":

<img width="637" alt="screenshot 2018-03-13 17 06 44" src="https://user-images.githubusercontent.com/1818628/37354035-f85b34ae-26e0-11e8-818c-a5e0bf78a9b9.png">

You then click "Neu Raumteiler" to create a new room offer / demand and then click "Ich habe Raum" to open the new room offer form. The url to access this directly is:

https://www.imgraetzl.at/wien/raumteiler/raum/new

Then towards the bottom, there is the "Website" field where people can enter a new url. The fix should auto-fix urls by prepending http:// if the user skips that part. So if someone enters just `www.example.com`, what is stored in the DB should be `http://www.example.com`. This can probably be done either in JavaScript or in Ruby on the backend.

In any case, it's important to not mess up the normal workflow when someone enters a url that already starts correctly, e.g. `http://www.example.com` or `https://www.example.com`.

The same thing applies to a room demand, that you access when you select "Ich suche Raum" which leads you to:

https://www.imgraetzl.at/wien/raumteiler/raumsuche/new

**Comment by anchal0997** [comment]
Hi @metakermit ,
The moment I Logged In on my localhost an error came saying 

> undefined method `numeric' for nil:NilClass

![screen shot 2018-04-06 at 11 26 26 pm](https://user-images.githubusercontent.com/21989049/38436432-36f68ece-39f2-11e8-8f90-346026f6dfa8.png)

Can you help me with this?

Anchal

**Comment by metakermit** [comment]
Hi Anchal,

did you run all the commands mentioned in the README to generate the
districts and Graetzls? Also, perhaps try logging in as another user
created in the seeds.rb script. I think max / secret is one of the accounts
in there.

Let me know if this doesn’t work.

**Comment by anchal0997** [comment]
@metakermit ,
![screen shot 2018-04-07 at 5 33 47 pm](https://user-images.githubusercontent.com/21989049/38454746-4b9d0fe0-3a8a-11e8-8e38-9337e01991ff.png)


Refreshing the page solved the problem somehow. I am facing another problem : the dropdown of room category isn't showing any options due to which I am unable to create any room. Can you help me with the same.

**Comment by metakermit** [comment]
Hey Anchal, great to hear you got the login working!

Yes, if you open the admin interface
http://localhost:3000/admin/room_categories you can create new room
categories.

**Comment by anchal0997** [comment]
Hey @metakermit ,

![screen shot 2018-04-07 at 6 52 01 pm](https://user-images.githubusercontent.com/21989049/38455374-d7a6222e-3a94-11e8-9c56-b6acdc38fa74.png)

It says no admin rights.

**Comment by metakermit** [comment]
Yes, you have to log in as one of the users who have a role "admin" or set
this role for your user. So your options are:

1) log in as e.g. max / secret or mirjam / secret – the demo users are
defined in im_graetzl/lib/tasks/db/populate.rake

```
    puts 'add users'
    users = ['malano', 'mirjam', 'jack', 'peter', 'jeanine', 'max', 'tawan']
    users.each do |user|
      new_user = User.new(
        username: user,
        first_name: user,
        last_name: user,
        email: user + '@example.com',
        password: 'secret',
        role: :admin,
        graetzl: Graetzl.find_by_name('Stuwerviertel'),
        confirmed_at: Time.now,
        slug: user)
      File.open(Rails.root+"lib/assets/avatars/#{user}.gif", 'rb') do |file|
        new_user.avatar = file
      end
      new_user.save(validate: false)
    end
```

2) set the role for your user to be admin. You should be able to do this
from the rails console. Something like:

rails c
u = User.find_by(username: 'yourusername')
u.role = :admin
u.save

**Comment by anchal0997** [comment]
Hey @metakermit ,

I tried printing the website of user in console of server at create but it's showing nil instead...but is adding the same in the database correctly using INSERT query.
Code :
![screen shot 2018-04-11 at 8 23 21 pm](https://user-images.githubusercontent.com/21989049/38635822-329b0058-3de4-11e8-9f9c-53d8f54420d8.png)

Output at terminal :
Website=> nil
![screen shot 2018-04-12 at 12 00 39 am](https://user-images.githubusercontent.com/21989049/38636000-a7ac96e0-3de4-11e8-83d9-f6519973f99b.png)

**Comment by metakermit** [comment]
Perhaps the user really has no website set. Keep in mind that both the room and the user can have a website.

```
➜  im_graetzl git:(master) ✗ rails c
Loading development environment (Rails 5.0.5)
2.3.4 :002 > room = RoomOffer.last
  RoomOffer Load (0.7ms)  SELECT  "room_offers".* FROM "room_offers" ORDER BY "room_offers"."id" DESC LIMIT $1  [["LIMIT", 1]]
 => #<RoomOffer id: 4, slogan: "Porro ut nulla tempora.", room_description: "Nihil reprehenderit adipisci rerum enim iste. Laud...", total_area: nil, rented_area: nil, owner_description: "Nihil reprehenderit adipisci rerum enim iste. Laud...", tenant_description: "Nihil reprehenderit adipisci rerum enim iste. Laud...", wants_collaboration: false, slug: "porro-ut-nulla-tempora-9a105622-44dc-49d6-9277-a6a...", user_id: 6, location_id: nil, created_at: "2018-01-18 18:04:00", updated_at: "2018-01-18 18:04:00", graetzl_id: 151, district_id: 6, cover_photo_id: "a003fdf6bafbaddddf63f97ab808ac02402748abf74e8c1ff6...", cover_photo_content_type: "image/jpeg", offer_type: "offering_room", first_name: "max", last_name: "max", website: "", email: "max@example.com", phone: "", avatar_id: nil, avatar_content_type: nil>
2.3.4 :004 > room.user.website
 => nil
2.3.4 :005 > room.website
 => ""
2.3.4 :006 > room.website = "www.example.com"
 => "www.example.com"
2.3.4 :007 > room.website
 => "www.example.com"
2.3.4 :008 > room.user.website
 => nil
```

In the case of this issue we are mainly considering the room's website – `room.website`.
