### ISSUE TITLE
Avatar Images of Room_Offers are often broken ...

### ISSUE THREAD

**Issue by malano** [imGraetzl/im_graetzl#227]
Lately the Avatar Images of Room-Offers are often missing and broken - See Screenshot ...
Just had a look - Seems that the Room-Offers with the broken Images don't have an Image uploaded. Thats strange, thought we had this as a "must-field". Just tried to create a Room-Offer without an Avatar - and indeed it was possible...

i will try to insert an fallback image. may you can have a look drazen why its not a must anymore? strange ...
<img width="1059" alt="bildschirmfoto 2018-03-13 um 19 17 11" src="https://user-images.githubusercontent.com/44798/37361842-25485c9a-26f4-11e8-9d57-1bcf053668a2.png">

**Comment by metakermit** [comment]
Ok, I’ll have time to look into this on Friday, Michael.

Hm… Yeah I also seem to remember we were saying we want to enforce avatar
uploads for users that don’t have them. Maybe we never implemented that
task in the end with all the other urgent things we had pre-Raumteiler
launch.
