### ISSUE TITLE
rake db:populate doesn't work on windows

### ISSUE THREAD

**Issue by peckomingo** [imGraetzl/im_graetzl#7]
following output:

$ rake db:populate
remove old data
check for graetzl and districts
add users
rake aborted!
Errno::EACCES: Permission denied @ unlink_internal - C:/Users/Peter/Development/Projekte/im_graetzl
/tmp/uploads/cache/e5bedf3799968443b06f57a9f3e634c7247e65831a2bfe009d9a89d4d5f1
C:/Users/Peter/Development/Projekte/im_graetzl/lib/tasks/db/populate.rake:32:in `block (3 levels) i
n <top (required)>'
C:/Users/Peter/Development/Projekte/im_graetzl/lib/tasks/db/populate.rake:19:in `each'
C:/Users/Peter/Development/Projekte/im_graetzl/lib/tasks/db/populate.rake:19:in `block (2 levels) i
n <top (required)>'
Tasks: TOP => db:populate
(See full trace by running task with --trace)

**Comment by tawan** [comment]
@peckomingo @klappradla  Vielleicht würde es für uns sogar Sinn machen [Vagrant](https://www.vagrantup.com/) aufzusetzen. Ich denke, es wird immer wieder zu Kompatilitätsproblemen kommen wenn auf Windows  / MacOS / und wer weis, vlt. in Zukunft auf Linux, entwickelt wird. Genau dafür wurde Vagrant geschaffen. Und da in Zukunft immer mehr Dependencies / Third-party Libraries dazu kommen werden, wird sich das Problem verschärfen.

Das Rails Projekt stellt auch eine [Vagrant-Box](https://github.com/rails/rails-dev-box) zur Verfügung. Das macht es natürlich super easy für Developer und Developerinnen einen Fix zu contributen ohne einen halben Tag lang erst einmal die Dev-Environment aufzusetzen.

Wenn ich die Zeit finde  versuche ich eventuell für uns eine Box zu basteln (ich wollte eh schon länger dieses Ding ausprobieren, würde auch in meiner jetztigen Arbeit Sinn machen), aber ich kanns halt nicht versprechen, weil der Initial-Aufwand eventuell hoch ist.

LG Tawan

**Comment by klappradla** [comment]
@tawan Mich würde da [Docker](http://docs.docker.com/mac/started/) noch mehr interessieren. Hier z.B. ein [Rails Quickstart mit Postgres](https://docs.docker.com/compose/rails/). Mir haben im letzten Monat unabhängig voneinander 3 Leute empfohlen auf Docker umzusteigen für das Projekt.

Wenn es Dich auch interessiert können wir es uns ja mal einen Tag anschauen, ob sich der Aufwand lohnt.

**Comment by tawan** [comment]
Ja, stimmt, die zwei Approaches sollten vergleichen. Soweit ich weis war Vagrant besser aufgestellt wenn es darum ging, das ganze Setup zu automatisieren, aber das könnte eventuell schon von Docker aufgeholt sein. Werd mir mal den Link durchlesen.

PS.: Umso mehr ich mich bei Docker einlese, umso mehr habe ich das Gefühl das das ein Gamechanger  ist.

**Comment by peckomingo** [comment]
@tawan @klappradla Ja blöd irgendwie dass es immer wieder mit Windows Probleme gibt. Am besten wäre ich switche auf OSX. Aber kostet halt Geld und wieder Zeit bis ich da drinnen und eingearbeitet bin.

Ich habe mir im Zuge meines Problems auch Varianten angesehen. Habe es gestern mit nitrous.io versucht. War mir zu wenig flexibel und man kann nicht wirklich alles installieren, hatte Problem postgis dafür zu finden. Aber trotzdem interessant so ein Cloud IDE.

Habe mir heute auch 1 Stunde Vagrant  (getting started) angesehen. Die Box läuft und das Prinzip scheint recht praktisch und nachvollziehbar für mich. Man arbeitet mit dem Host OS am Code aber ausgeführt wird es im Guest OS (in meinem Fall Ubuntu). Ich habe es aber noch nicht mit unserem Projekt versucht, weil mir noch nicht ganz klar ist wie ich das am besten angehe/zusammenführen soll. Schaut aber jetzt auch nicht allzu komplex aus.

Grundsätzlich würde ich schon eine Lösung mit Vagrant oder auch Docker begrüssen. Scheint ja auch recht zukunftsträchtig und plausibel als Philosophie zum gemeinsamen Entwickeln.
Es soll uns halt nicht viel Zeit kosten und uns aufhalten an unserem Projektfortschritt.

Also wenn ihr wirklich einen Tag tüfteln wollt und etwas dabei rauskommt, wär es schon cool. Nachdem du es ja auch für deinen anderen Job brauchst @tawan bietet es sich ja an.
Lasst uns nächste Woche kurz skypen deswegen.

**Comment by klappradla** [comment]
Permission Issue scheint ein bekanntes aber ungelöstes Problem von refile zu sein: https://github.com/refile/refile/issues/133

**Comment by peckomingo** [comment]
Kurzes Update. Ich habe ja das permission problem beim upload

**Comment by klappradla** [comment]
@peckomingo Upload via Form auf der Seite oder via Raketask ist die gleiche Funktionalität. Wenn das eine geht, geht auch das andere.
Würde die Issue wieder öffnen, oder inwiefern hat sich das Problem jetzt erledigt?

**Comment by peckomingo** [comment]
@klappradla nein beides geht nicht.
Was jedoch funktioniert sind die Outputs beim Upload von der Ajax Funktionalität. Also "upload started, upload complete" etc. Damit könnte ich zumindest doch mal die Interfacekomponente von dem Uploadfeld angehen... hoffe ich...

**Comment by klappradla** [comment]
Still problem with refile:
````
==> default:    -> 0.0025s
==> default: -- initialize_schema_migrations_table()
==> default:    -> 0.0066s
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: rake aborted!
==> default: Errno::ETXTBSY: Text file busy @ unlink_internal - /vagrant/tmp/uploads/cache/a819e4368836836ac8d224b20673ad2c934e69ea3fa2fb07aa2f92d535cf
==> default: /vagrant/lib/tasks/db/populate.rake:32:in `block (3 levels) in <top (required)>'
==> default: /vagrant/lib/tasks/db/populate.rake:19:in `each'
==> default: /vagrant/lib/tasks/db/populate.rake:19:in `block (2 levels) in <top (required)>'
==> default: Tasks: TOP => db:populate
==> default: (See full trace by running task with --trace)
==> default: remove old data
==> default: check for graetzl and districts
==> default: add users
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by klappradla** [comment]
Solving this through [using RSync for syncing folders](https://docs.vagrantup.com/v2/synced-folders/rsync.html) in Vagrant.

Prerequisites:
* [RSync](https://rsync.samba.org/)
* maybe use [MYSY2](http://sourceforge.net/projects/msys2/) as a shell on windows (minimal Cycwin Version, easy to install RSync via [Pacman](https://wiki.archlinux.org/index.php/Help:Reading#Installation_of_packages))

**Comment by klappradla** [comment]
Closing this as it now works in a Vagrant setup introduced in f99f55ef2d2dbe4cf3bc4d4185501e39e426e17f

**Comment by peckomingo** [comment]
solution http://stackoverflow.com/questions/32377279/text-file-busy-unlink-internal
